environment:
  matrix:
    - MINICONDA: C:\Miniconda-x64
    - MINICONDA: C:\Miniconda35-x64
    - MINICONDA: C:\Miniconda36-x64
    - MINICONDA: C:\Miniconda37-x64
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update --quiet conda pip
  - conda info --all
  - conda install --only-deps gwpy
  - python ci\\parse-conda-requirements.py requirements-dev.txt -o conda-reqs.txt
  - conda install --yes --file conda-reqs.txt
build_script:
  - python -m pip install .
test_script:
  - python -m pytest --pyargs gwpy --cov gwpy
